### ISSUE TITLE
Update website background color to match mint green design

### ISSUE THREAD

**Issue by RahulKarra** [RahulKarra/Soil-Classification-Crop-Recommendation#1]
## Background Color Update Request

We need to update the website's background color to match the mint green color scheme shown in the testimonials section.

## Current Design
<img alt="image2" width="1919" src="https://github.com/user-attachments/assets/e840c4f7-c17f-46fc-88d3-37d345089f73" />

## Color Details
The background should use the light mint green color as seen in the "What Parents Say" section of the website. This color creates a soft, soothing environment that's perfect for an early education website.

## Implementation Details

Add the following CSS to the website's main stylesheet:

```css
body {
    background-color: #f0f9f6; /* Light mint green - closest approximation */
}

/* For the testimonials section, ensure consistency */
.testimonials-section {
    background-color: #f0f9f6;
}
```

## Areas to Update
1. Main background color
2. Ensure consistency across all sections
3. Check contrast with text and other elements

## Testing Requirements
1. Verify the color matches the design reference
2. Check text readability against new background
3. Test across different devices and screen sizes
4. Ensure proper contrast ratios for accessibility

## Expected Outcome
- A consistent, soothing mint green background throughout the website
- Improved visual harmony with the existing design elements
- Maintained readability of all text content
